virts-2892: Knowledge Service Documentation
mitre/fieldmanual pull request #83
Opened 2021-09-29 13:33 UTC by ArtificialErmine

## Description

Adds some documentation regarding the Knowledge Service to "How to Build Planners".

## Type of change
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How Has This Been Tested?

It's just documentation changes, so I technically haven't tested this. The core code  being documented has been in use for a while, though, so it's pretty tested at this point.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works

2021-09-29 19:44 UTC, clenk requested changes
Maybe additional details should be added to https://caldera.readthedocs.io/en/latest/Basic-Usage.html#facts as well?

Stuff that would be helpful to document somewhere:
 - fact properties other than name/value/score (already explained on the Basic Usage page)
 - the different origin types and what they mean

We should update any instances of a fact's `trait` in the docs to `name`.

I would make the order of methods consistent between fact, relationship, and rule. Currently the fact table starts with the `add_` method but the relationship one starts with the `get_` method.

Also, and I know it's not tied to this ticket, but there's a typo in the second sentence under the `Operation Utilities` section: `follow` should be `following`.

2021-09-29 19:44 UTC, clenk commented on sphinx-docs/How-to-Build-Planners.md
> +All objects added to the Knowledge service are checked against existing objects in order to enforce de-duplication, with one caveat. As origin is tracked for facts generated by links in the current i
```suggestion
All objects added to the Knowledge service are checked against existing objects in order to enforce de-duplication, with one caveat. As origin is tracked for facts generated by links in the current implementation, this means duplicate facts created during different operations can exist in the fact store simultaneously. Facts/Relationships are usually automatically added to the fact store by `Link` objects as part of the process of parsing output, though they can be added manually should the need arise.
```

2021-09-29 20:12 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +The Knowledge Service stores data persistently in the same manner that Caldera's internal Data sService does (by writing it to a file on shutdown), and can be cleared in much the same way if necessar
Thanks for catching that.

2021-09-29 20:12 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +The following methods are present and supported in the Knowledge Service:
Makes sense.

2021-09-29 20:14 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +As of Caldera V4.0, a new service has been added to the core of Caldera for use with planners and other components that make use of facts: the Knowledge Service. This service provides a variant of th
That would be more straightforward, so I'll swap things over. The former would have been potentially useful for developers, which is why I original went with that, but it should be fairly obvious anyway.

2021-09-29 20:15 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +Typically, users should not need to interact with this service directly, as common usage patterns are already baked into core objects such as `Link()`, `Agent()`, and `Operation()`, but the service c
It was mainly to denote the referenced things were literal objects. If you don't think they're necessary I'll drop them.

2021-09-29 20:15 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +All objects added to the Knowledge service are checked against existing objects in order to enforce de-duplication, with one caveat. As origin is tracked for facts generated by links in the current i
That's definitely more clear.

2021-09-29 20:16 UTC, ArtificialErmine commented on sphinx-docs/How-to-Build-Planners.md
> +
We never implemented one - rules shouldn't be changed nearly as often as the other objects in the knowledge service. If we see a use case where changing them would be helpful in the future, I think it wouldn't be too hard to add in, but until then, I'm inclined to leave things as they are.

2021-09-29 21:04 UTC, ArtificialErmine commented
The tables might not be working in the generated version - can you verify that they do on your end, @clenk? They work fine in markdown, but the generated html is having trouble with it on my end (and based on your previous comment it's possible that they worked fine in the html for you),

2021-09-29 21:19 UTC, ArtificialErmine commented
> The tables might not be working in the generated version - can you verify that they do on your end, @clenk? They work fine in markdown, but the generated html is having trouble with it on my end (and based on your previous comment it's possible that they worked fine in the html for you),

I've removed the tables and reverted to using a bulleted list. The built-in triggers for generating tables in Sphinx don't appear to be working, and rendering standard Markdown tables doesn't seem to be possible without more libraries, which I'd rather avoid using. It does look way uglier this way, though.

2021-09-30 17:35 UTC, clenk approved these changes
Looks good, checked it locally on my end. Using bulleted lists keeps it consistent with the rest of the page.

There is a way to do tables without any additional Sphinx plugins. The markdown parser we're already using, Recommonmark, comes with something called [AutoStructify](https://recommonmark.readthedocs.io/en/latest/index.html#autostructify) that converts markdown to rst before converting to HTML. It has an option, `enable_eval_rst` that lets you stick rst in your markdown. But rst tables won't show up right if viewing the markdown in an IDE or on GitHub, and are clunkier to maintain (have to do the line wrapping manually).

At the same time, looks like Recommonmark is no longer maintained and [ReadTheDocs encourages](https://github.com/readthedocs/recommonmark/issues/221) moving to the Myst parser instead. And the Myst parser supports markdown tables.

But that's a bigger issue than this PR, which is good to go in my book. :)

2021-10-05 13:50 UTC, merged